### ISSUE TITLE
zest-dipri repo empty

### ISSUE THREAD

**Issue by Spr1n9T1me** [QRXqrx/dipri-artifacts#1]
Hi! It seems that the Zest implemention of DiPri is empty with this link in README.md: https://github.com/QRXqrx/dipri-artifacts/blob/41f8f7887dc74222e78679c0c3f8162138da7cb4/README.md?plain=1#L31
Is it still open source?

**Comment by Zzhiter** [comment]
懂得都懂，你去看他Github活动记录，两次。
一次是加入Github；另一次是在Zest的作者下面提了个issue。
也就是说这个仓库压根都没有创建过。
![image](https://github.com/QRXqrx/dipri-artifacts/assets/61727602/de3c08b2-b6af-40d9-837a-93e4cd139fbf)

**Comment by QRXqrx** [comment]
> Hi! It seems that the Zest implemention of DiPri is empty with this link in README.md:
> 
> https://github.com/QRXqrx/dipri-artifacts/blob/41f8f7887dc74222e78679c0c3f8162138da7cb4/README.md?plain=1#L31
> 
> 
> Is it still open source?

Thanks for your interest in DiPri! 

Apologies for our silly mistakes! The link was previously broken as we named it wrongly and have made a renaming. You can now access the Zest implementation through [https://github.com/YangDingNY/zest-dipri](https://github.com/YangDingNY/zest-dipri). Please note that this repository may be closed later. We have moved all the artifacts of DiPri to this account [https://github.com/isefuzz](https://github.com/isefuzz) for a long archive. You can of course find Zest-DiPri at [https://github.com/isefuzz/zest-dipri](https://github.com/isefuzz/zest-dipri).
